version: '3.3'
services:
  mkdocs_cookingrecipes:
    container_name: "mkdocs_cookingrecipes"
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 18080:80
    restart: unless-stopped

