name: 'build mkdocs'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@main
      - run: touch "$GITHUB_WORKSPACE/testfile.test"
