name: 'build mkdocs'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@main
      - name: "Install dependencies"
        working-directory: "mkdocs/bin"
        run: |
          source ./activate
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs mkdocs-exclude-search mkdocs-material-extensions mkdocs-material mkdocs-pdf-export-plugin
          python3 -m pip install -f requirements.txt
      - name: Build site
        run: python3 -m mkdocs build
      - name: Stop Container
        working-directory: "./docker"
        run: "docker-compose down || true"
      - name: Delete images
        run: "docker image prune -a -f"
      - name: "Start Container"
        working-directory: "./docker"
        run: "docker-compose up --detach --force-recreate"
