name: 'build mkdocs'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@main
      - name: Stop Container
        run: "docker-compose down || exit 0"
      - name: Remove old image
        run: "docker image prune -a"
      - name: "Start Container"
        run: "docker-compose up --detach --force-recreate"
