name: 'build mkdocs'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@main
      - run: "cd $GITHUB_WORKSPACE"
      - run: |
          source $GITHUB_WORKSPACE/mkdocs/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs mkdocs-exclude-search mkdocs-material-extensions mkdocs-material 
          python3 -m mkdocs build
      - run: "cd $GITHUB_WORKSPACE/docker"
      - run: "docker-compose down"
      - run: "docker-compose up"

