name: 'build mkdocs'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@main
      #- run: pip install mkdocs
      - run: echo "Hello everyone this is a test"
      - run: touch "/tmp/testfile.test"
