name: 'build mkdocs'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@main
      - run: "cd $GITHUB_WORKSPACE"
      - run: source "$GITHUB_WORKSPACE/mkdocs/bin/activate"
      - run: "python3 -m pip install mkdocs"
      - run: "mkdocs build"
      - run: "docker-compose down -f $GITHUB_WORKSPACE/docker/docker-compose.yml"
      - run: "docker container rm mkdocs_cookingrecipes"
      - run: "docker image rm docker-mkdocs_cookingrecipes --force"
      - run: "docker-compose up -f $GITHUB_WORKSPACE/docker/docker-compose.yml"
      - run: "deactivate"
